Enable usage of 410 AFS space for snapshotting.

diff --git a/landslide b/landslide
--- a/landslide
+++ b/landslide
@@ -37,9 +37,11 @@ elif [ "$RV" = "$ID_EXIT_CTRL_C" ]; then
 	echo
 fi
 
-SNAPSHOT_DIR="/dev/shm" # TODO
+SNAPSHOT_DIR="/afs/cs/academic/class/15410-s15/user/$USER/mygroup/landslide/"
+TEMP_SNAP_DIR="/dev/shm"
 SNAPSHOT_NAME="ls-snap-$USER-$SUFFIX.tar.bz2"
-tar cvjf "$SNAPSHOT_DIR/$SNAPSHOT_NAME" \
+umask 077
+tar cvjf "$TEMP_SNAP_DIR/$SNAPSHOT_NAME" \
 	--exclude="pebsim/p2-basecode/410user/*" \
 	--exclude="pebsim/p2-basecode/410kern/*" \
 	--exclude="pebsim/p2-basecode/temp/*" \
@@ -58,5 +60,12 @@ tar cvjf "$SNAPSHOT_DIR/$SNAPSHOT_NAME" \
 	--exclude="*kernel.strip" \
 	--exclude="*kernel.log" \
 	"./" >/dev/null
+mv "$TEMP_SNAP_DIR/$SNAPSHOT_NAME" "$SNAPSHOT_DIR"
+MV_RV=$?
+if [ "$MV_RV" != "0" ]; then
+	echo -e "\033[01;31mFailed to save snapshot ($TEMP_SNAP_DIR/$SNAPSHOT_NAME) into 410 AFS space ($SNAPSHOT_DIR). Please email Ben <bblum@cs.cmu.edu> for support, including this snapshot as an attachment."
+	echo -e "\033[00m(landslide's exit code was $RV)"
+	exit 1
+fi
 
 exit $RV
